s3:
  bucketName: jaeger-s3-test
  spansPrefix: spans/
  operationsPrefix: operations/
  bufferDuration: 1s
  operationsDedupeDuration: 1s
  emptyBucket: true
athena:
  databaseName: default
  spansTableName: jaeger_spans
  operationsTableName: jaeger_operations
  outputLocation: s3://jaeger-s3-test-results/
  workGroup: jaeger
  maxSpanAge: 336h
  dependenciesQueryTtl: 24h
  dependenciesPrefetch: true
  servicesQueryTtl: 10s
